# Generated by Django 4.1.7 on 2023-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='themes',
            field=models.CharField(choices=[('WD', 'Мир'), ('PL', 'Политика'), ('BS', 'Бизнес'), ('HL', 'Здоровье'), ('CL', 'Культура'), ('SC', 'Общество'), ('AC', 'Проишествия'), ('SP', 'Спорт'), ('IT', 'ИТ'), ('SN', 'Наука'), ('EC', 'Экономика')], max_length=2, unique=True),
        ),
    ]
