# Generated by Django 4.2 on 2023-04-22 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0002_alter_category_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
